#spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.jpa.hibernate.ddl-auto=none
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#jwt.secret=MySuperSecretKey12345


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/releases/v0.0.1/db.changelog-master.yaml
jwt:
  secret: "MySuperSecretKey12345"


#  spring:
#    jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        default_schema: public
#        order_inserts: true
#        enable_lazy_load_no_trans: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        jdbc:
#          lob:
#            non_contextual_creation: true
#          batch_size: 20
#        generate_statistics: false
#    show-sql: true
#    database: postgresql
#    datasource:
#      driver-class-name: org.postgresql.Driver
#      url: jdbc:postgresql://localhost:5432/auth_service
#      username: postgres
#      password: postgres
#    liquibase:
#      default_schema: public
#      enabled: true
#      change-log: classpath:db/changelog/releases/v0.0.1/db.changelog-master.yaml
#  jwt:
#    secret: "MySuperSecretKey12345"

